-- Create schema.
create table
    messages (
        id integer primary key generated by default as identity,
        uuid uuid not null unique,
        sender varchar not null,
        recipient varchar not null,
        payload varchar not null,
        client_id varchar not null
    )
;

create table
    events (
        uuid uuid not null references messages (uuid),
        status varchar not null,
        ts timestamp
        with
            time zone,

        primary key (uuid, status)
    )
;
